### ISSUE TITLE
Partially initialized module

### ISSUE THREAD

**Issue by samipanyam** [AshwinPathi/claude-api-py#13]
I tried using the pypi installation of the module, but it gives me 

Traceback (most recent call last):
  File "/home/sami/backup/alvin-work/claude.py", line 2, in <module>
    from claude import claude_client
  File "/home/sami/backup/alvin-work/claude.py", line 2, in <module>
    from claude import claude_client
ImportError: cannot import name 'claude_client' from partially initialized module 'claude' (most likely due to a circular import) (/home/sami/backup/alvin-work/claude.py)

The pypi installation worked fine.

**Comment by samipanyam** [comment]
I was being stupid
